# Generated by Django 4.1.6 on 2023-03-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='image',
            new_name='url',
        ),
    ]
