# Generated by Django 4.1.6 on 2023-02-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parksapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildlifeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wildlife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('information', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=5000)),
                ('wildlife_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_wildlife', to='parksapi.wildlifegroups')),
            ],
        ),
    ]
