# Generated by Django 4.1.6 on 2023-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parksapi', '0002_rename_image_campground_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
