# Generated by Django 4.1.6 on 2023-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parksapi', '0003_campground_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildlife',
            old_name='image',
            new_name='url',
        ),
    ]
