# Generated by Django 4.1.6 on 2023-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parksapi', '0004_rename_image_wildlife_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildlife',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
